version: '3.9'

x-app:
  &app
  volumes:
    - ./app/composer.json:/var/www/code/composer.json
    - ./app/composer.lock:/var/www/code/composer.lock
    - ./app/symfony.lock:/var/www/code/symfony.lock
    - ./app/bin:/var/www/code/bin
    - ./app/config:/var/www/code/config
    - ./app/public:/var/www/code/public
    - ./app/src:/var/www/code/src

services:
  app1:
    <<: *app

  app2:
    <<: *app

  acceptance-tests:
    volumes:
      - ./acceptance-tests/behat.yaml:/var/www/code/behat.yaml
      - ./acceptance-tests/composer.json:/var/www/code/composer.json
      - ./acceptance-tests/composer.lock:/var/www/code/composer.lock
      - ./acceptance-tests/features:/var/www/code/features
      - ./acceptance-tests/src:/var/www/code/src
