version: '3.9'

services:
  app:
    image: fefas/be-rinha-2023/app
    build:
      context: app
      args:
        BUILD_TARGET: dev
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: be_rinha_2023
      DB_USER: fefas
      DB_PASS: secret
    depends_on:
      db: { condition: service_healthy }
    healthcheck:
      test: [ "CMD", "curl", "http://localhost:9000" ]
      start_period: 0s
      interval: 1s
      timeout: 1s
      retries: 5

  db:
    image: fefas/be-rinha-2023/db
    build:
      context: db
    environment:
      POSTGRES_DB: be_rinha_2023
      POSTGRES_USER: fefas
      POSTGRES_PASSWORD: secret
    ports: [ "5432:5432" ]
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U fefas" ]
      interval: 10s
      timeout: 5s
      retries: 5
