version: '3.9'

services:
  acceptance-tests:
    image: fefas/be-rinha-2023/acceptance-tests
    build:
      context: acceptance-tests
    environment:
      APP_URL: http://nginx:80
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: be_rinha_2023
      DB_USER: fefas
      DB_PASS: secret
    depends_on:
      nginx: { condition: service_healthy }
    volumes:
      - ./acceptance-tests/behat.yaml:/var/www/code/behat.yaml
      - ./acceptance-tests/composer.json:/var/www/code/composer.json
      - ./acceptance-tests/composer.lock:/var/www/code/composer.lock
      - ./acceptance-tests/features:/var/www/code/features
      - ./acceptance-tests/src:/var/www/code/src

  app:
    volumes:
      - ./app/composer.json:/var/www/code/composer.json
      - ./app/composer.lock:/var/www/code/composer.lock
      - ./app/symfony.lock:/var/www/code/symfony.lock
      - ./app/bin:/var/www/code/bin
      - ./app/config:/var/www/code/config
      - ./app/public:/var/www/code/public
      - ./app/src:/var/www/code/src

